POST  http://localhost:5000/users/createUser HTTP/1.1
content-type: application/json

{
    "email": "alice4@prisma.io",
    "nom": "Alice",
    "password": "password123",
    "role": "AUTHOR"
}

### get users
GET   http://localhost:5000/users/getUsers HTTP/1.1
### get user
GET   http://localhost:5000/users/getUser?id=2 HTTP/1.1

### modify user
patch   http://localhost:5000/users/modifyUser HTTP/1.1
content-type: application/json

{
    "id": "1",
    "nom": "dddddddd",
    "email": "aaaaaaaaa@prisma.io",
    "password": "password123",
    "role": "AUTHOR"
    }

### delete user
DELETE   http://localhost:5000/users/deleteUser HTTP/1.1
content-type: application/json

{
    "id" : 1
}