POST  http://localhost:5000/article HTTP/1.1
content-type: application/json

{
"contenu"       :"first Article",
"titre"         :"article 2 ",
"image"         :"",
"utilisateurId" :"1",
"published"     :"true"

}

### get articles with take and skip 
GET   http://localhost:5000/article?&take=10&skip=1 HTTP/1.1

### get onr article
GET   http://localhost:5000/article/4 HTTP/1.1

### modify article
patch   http://localhost:5000/article/1 HTTP/1.1
content-type: application/json

{
"contenu"       :"first Article",
"titre"         :"article 2 modified ",
"image"         :"",
"utilisateurId" :"1",
"published"     :"true"
    }

### delete article
DELETE   http://localhost:5000/article/1 HTTP/1.1



###
GET   http://localhost:5000/article/user/1/?&take=10&skip=0 HTTP/1.1